---
title: Desenvolvedor Web | Beto da Silva
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: betodasilvajr@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: "/blog"
url: ''
permalink: "/:categories/:title/"
twitter_username: betodslv
github_username: betodasilva
instagram_username: betodslv
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
